#!/bin/bash

# if the user inputted a positional arg, use that as the component dash name.
# otherwise, prompt.
if [ -n "$1" ]; then
  NAMEDASH="$1"
  echo "Cool, we're making a $NAMEDASH helper."
else
  echo "Let's make a new helper."
  printf "Enter the name of your helper, in dash-case: "; read NAMEDASH
fi

NAMEUPPERCAMEL="$(echo "$NAMEDASH" | perl -pe 's/(^|-)./uc($&)/ge;s/_//g' | sed 's/-//g')"

first="$(echo $NAMEUPPERCAMEL | cut -c1 | tr [A-Z] [a-z])"
second="$(echo $NAMEUPPERCAMEL | cut -c2-)"
NAMECAMEL="$first$second"

mkdir -p src/helpers/$NAMEDASH
cat <<EOF > src/helpers/$NAMEDASH/index.js
export default function $NAMECAMEL() {
  return true
}
EOF

cat <<EOF > src/helpers/$NAMEDASH/test.js

import assert from 'assert';
import $NAMECAMEL from './index';

describe('$NAMEDASH', function() {
  it('should work', function() {
    assert.equal($NAMECAMEL(), true);
  });
});

EOF

echo "Created helper:"
echo "Script is located here: src/helpers/$NAMEDASH/index.js"
echo "Tests are located here: src/helpers/$NAMEDASH/test.js"
